### ISSUE TITLE
Stack times?

### ISSUE THREAD

**Issue by Jonwheeler** [jiahuang/d3-timeline#46]
Firstly thanks for this library, I've been enjoying using it on an internal project.

I was wondering if there is a way to stack the times as well as the timeline items so that you can see overlapping data?

**Comment by jiahuang** [comment]
Don't think you can do this at the moment, though if you figure it out please submit a PR.

**Comment by inodb** [comment]
I'm thinking about tackling this issue. How about instead of stacking times like:
```javascript
// create y mapping for stacked graph
if (stacked && Object.keys(yAxisMapping).indexOf(index) == -1) {
  yAxisMapping[index] = maxStack;
  maxStack++;
}
```
We would set a stack attribute per time point. That stack attribute is set by grouping the times by overlap and adding one if necessary. If we iterate over all labeled "tracks" in the outer loop I think it should work. Here in semi python pseudocode:
```python
stack = 0
for times in tracks:
    max_stack_overlap = stack
    for overlapgroup in get_overlap(times):
         stack_overlap = stack
         for timepoint in overlap_group:
             timepoint.stack = stack_overlap
             stack_overlap +=  1
             if timepoint.stack > max_stack_overlap:
                 max_stack_overlap = timepoint.stack
    stack = max_stack_overlap + 1
```
Does that make sense?

**Comment by inodb** [comment]
I implemented the idea here: https://github.com/inodb/clinical-timeline-1/commit/c9a3e2810334c6ee3cfa4659d52bda6a9478c41a. Seems to work so far - I'll try to make a PR
